"""Add missing columns

Revision ID: 33a42cb91b38
Revises: 
Create Date: 2025-03-23 14:26:43.687918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33a42cb91b38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calendar', type_='foreignkey')
    op.drop_column('calendar', 'request_id')
    op.add_column('prescription', sa.Column('patient_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'prescription', 'patient', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prescription', type_='foreignkey')
    op.drop_column('prescription', 'patient_id')
    op.add_column('calendar', sa.Column('request_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'calendar', 'request', ['request_id'], ['id'])
    # ### end Alembic commands ###
