"""Fix patient typo

Revision ID: d526b866f869
Revises: ccf66623b0e5
Create Date: 2025-04-03 17:42:28.624703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd526b866f869'
down_revision: Union[str, None] = 'ccf66623b0e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_history', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.drop_constraint('appointment_history_pacient_id_fkey', 'appointment_history', type_='foreignkey')
    op.create_foreign_key(None, 'appointment_history', 'patient', ['patient_id'], ['id'])
    op.drop_column('appointment_history', 'pacient_id')
    op.add_column('family_relation', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('family_relation_patient_id_fkey', 'family_relation', type_='foreignkey')
    op.drop_constraint('family_relation_related_id_fkey', 'family_relation', type_='foreignkey')
    op.drop_column('family_relation', 'related_id')
    op.drop_column('family_relation', 'patient_id')
    op.drop_column('family_relation', 'relation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_relation', sa.Column('relation', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('family_relation', sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('family_relation', sa.Column('related_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('family_relation_related_id_fkey', 'family_relation', 'patient', ['related_id'], ['id'])
    op.create_foreign_key('family_relation_patient_id_fkey', 'family_relation', 'patient', ['patient_id'], ['id'])
    op.drop_column('family_relation', 'id')
    op.add_column('appointment_history', sa.Column('pacient_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appointment_history', type_='foreignkey')
    op.create_foreign_key('appointment_history_pacient_id_fkey', 'appointment_history', 'patient', ['pacient_id'], ['id'])
    op.drop_column('appointment_history', 'patient_id')
    # ### end Alembic commands ###
