name: Frontend CI/CD

on:
  push:
    branches:
      - main # Spustí se pouze při push do main
    paths:
      - "frontend/**" # Spustí se pouze pokud se mění něco ve frontend složce
  pull_request:
    branches:
      - main # Spustí se na Pull Request směřující do main
    paths:
      - "frontend/**" # Spustí se pouze pokud se mění něco ve frontend složce

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend # Nastaví výchozí adresář na ./frontend

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install -g pnpm && pnpm install

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

  cd:
    needs: ci # Zajistí, že deploy běží až po dokončení CI pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: "./frontend/.next"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 10
